const MovieTypes = {
  GET_MOVIE : 'GET_MOVIE',
  GET_MOVIE_DETAILS: 'GET_MOVIE_DETAILS',
  FETCH_START: 'FETCH_START',
  FETCH_SUCCESS:'FETCH_SUCCESS',
  FETCH_DETAIL_SUCCESS:'FETCH_DETAIL_SUCCESS',
  FETCH_FAILURE:'FETCH_FAILURE',
}

export default MovieTypes;